-- MySQL Script generated by MySQL Workbench
-- 09/25/15 10:30:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_news` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_news` ;

-- -----------------------------------------------------
-- Table `db_news`.`Channels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_news`.`Channels` ;

CREATE TABLE IF NOT EXISTS `db_news`.`Channels` (
  `id` BIGINT NOT NULL,
  `cid` VARCHAR(20) NOT NULL,
  `cname` VARCHAR(100) NULL,
  `subnum` VARCHAR(10) NULL DEFAULT 0,
  `extra` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_news`.`News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_news`.`News` ;

CREATE TABLE IF NOT EXISTS `db_news`.`News` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `source` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  `time` TIMESTAMP NULL,
  `snapDetail` VARCHAR(200) NULL,
  `icon` VARCHAR(100) NULL,
  `extra` TEXT NULL,
  `cid` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `channelId_idx` (`cid` ASC),
  CONSTRAINT `channelId`
    FOREIGN KEY (`cid`)
    REFERENCES `db_news`.`Channels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '<double-click to overwrite multiple objects>';


-- -----------------------------------------------------
-- Table `db_news`.`NewsSection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_news`.`NewsSection` ;

CREATE TABLE IF NOT EXISTS `db_news`.`NewsSection` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `newsId` BIGINT NOT NULL,
  `sectionOrder` INT NOT NULL DEFAULT 0,
  `sectionDetail` TEXT NULL,
  `setionImg` VARCHAR(100) NULL,
  `extra` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `newsId_idx` (`newsId` ASC),
  CONSTRAINT `newsId`
    FOREIGN KEY (`newsId`)
    REFERENCES `db_news`.`News` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '<double-click to overwrite multiple objects>';


-- -----------------------------------------------------
-- Table `db_news`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_news`.`User` ;

CREATE TABLE IF NOT EXISTS `db_news`.`User` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `nickName` VARCHAR(45) NOT NULL,
  `headIcon` VARCHAR(45) NULL,
  `extra` TEXT NULL,
  `time` TIMESTAMP NULL,
  `extra` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '<double-click to overwrite multiple objects>';


-- -----------------------------------------------------
-- Table `db_news`.`UserFavourite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_news`.`UserFavourite` ;

CREATE TABLE IF NOT EXISTS `db_news`.`UserFavourite` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uid` BIGINT NOT NULL,
  `nid` BIGINT NOT NULL,
  `time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `nid_idx` (`nid` ASC),
  INDEX `uid_idx` (`uid` ASC),
  CONSTRAINT `favUser`
    FOREIGN KEY (`uid`)
    REFERENCES `db_news`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `favNews`
    FOREIGN KEY (`nid`)
    REFERENCES `db_news`.`News` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '<double-click to overwrite multiple objects>';


-- -----------------------------------------------------
-- Table `db_news`.`UserComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_news`.`UserComment` ;

CREATE TABLE IF NOT EXISTS `db_news`.`UserComment` (
  `id` BIGINT NOT NULL,
  `uid` BIGINT NOT NULL,
  `nid` BIGINT NOT NULL,
  `comment` TEXT NULL,
  `time` TIMESTAMP NULL,
  `extra` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `uid_idx` (`uid` ASC),
  INDEX `nid_idx` (`nid` ASC),
  CONSTRAINT `commentUser`
    FOREIGN KEY (`uid`)
    REFERENCES `db_news`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commentNews`
    FOREIGN KEY (`nid`)
    REFERENCES `db_news`.`News` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '<double-click to overwrite multiple objects>';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
